name: ci

on:
  pull_request:
  push:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo debconf-set man-db/auto-update false
          sudo rm /var/lib/man-db/auto-update
          sudo apt update && sudo apt install clang-format
          find -iname "*.h" -o -iname "*.c" -o -iname "*.cpp" | xargs clang-format --dry-run --Werror
